spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    generate-ddl: true
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<postgres>>}
    hikari:
      schema: user_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS user_schema
      connection-timeout: 30000
      maximum-pool-size: 10
    hibernate:
      ddl-auto: none

app:
  security:
    type: db
  jwt:
    secret: someSecretKey
    tokenExpiration: 3m
    refreshTokenExpiration: 30m
