spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:<<testtest>>}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    hibernate:
      ddl-auto: update
